--- 
title: "Rental Pricing Analysis"
author: " Deepesh Dinesh Theruvath Kanhangad, Hari Prasad Renganathan, Karveandhan Palanisamy"
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
---
--- 
title: "Rental Pricing Analysis"
author: " Deepesh Dinesh Theruvath Kanhangad, Hari Prasad Renganathan, Karveandhan Palanisamy"
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
---
```{r include=FALSE, cache=FALSE}
knitr::opts_chunk$set(
  echo = FALSE,
  message = FALSE,
  warning = FALSE
)
```

# Introduction


<!--chapter:end:index.Rmd-->

```{r include=FALSE, cache=FALSE}
knitr::opts_chunk$set(
  echo = FALSE,
  message = FALSE,
  warning = FALSE
)
```
# Data sources


<!--chapter:end:02-data.Rmd-->

```{r include=FALSE, cache=FALSE}
knitr::opts_chunk$set(
  echo = FALSE,
  message = FALSE,
  warning = FALSE
)
```
# Data transformation

<!--chapter:end:03-cleaning.Rmd-->

```{r include=FALSE, cache=FALSE}
knitr::opts_chunk$set(
  echo = FALSE,
  message = FALSE,
  warning = FALSE
)
```
```{r, fig.width=20, fig.height=8}

plot_missing <- function(dataf,percent){
  
  if(sum(is.na(dataf))>0){
  
missing.values <- dataf %>%
    gather(key = "key", value = "val") %>%
    mutate(is.missing = is.na(val)) %>%
    group_by(key, is.missing) %>%
    summarise(num.missing = n()) %>%
    filter(is.missing==T) %>%
    select(-is.missing) %>%
    arrange(desc(num.missing)) 

missing_val.plot <- missing.values %>%
  ggplot() +
    geom_bar(aes(x=key, y=num.missing, fill='tomato2'), stat = 'identity') +
   scale_fill_manual(name = "", 
                        values = c('tomato2'), labels = c("Missing"))+
    labs(x='variable', y="number of missing values", title='Number of missing values') +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))


missing.values <- dataf %>%
  gather(key = "key", value = "val") %>%
  mutate(isna = is.na(val)) %>%
  group_by(key) %>%
  mutate(total = n()) %>%
  group_by(key, total, isna) %>%
  summarise(num.isna = n()) %>%
  mutate(pct = num.isna / total * 100)


levels <-
    (missing.values  %>% filter(isna == T) %>% arrange(desc(pct)))$key



percentage_missing.plot <- missing.values %>%
      ggplot() +
        geom_bar(aes(x = reorder(key, desc(pct)), 
                     y = pct, fill=isna), 
                 stat = 'identity', alpha=0.8) +
      scale_x_discrete(limits = levels) +
      scale_fill_manual(name = "", 
                        values = c('steelblue3', 'tomato2'), labels = c("Present", "Missing")) +
      coord_flip() +
      labs(title = "Percentage of missing values", x =
             'Variable', y = "% of missing values")


if (percent==TRUE){
  return(grid.arrange(missing_val.plot,percentage_missing.plot, ncol = 2))
}
else{
  return(missing_val.plot)
}

  }
  else{
    return('No Missing Values in the entire dataframe')
    
  }
}
```


```{r, fig.width=20, fig.height=8}
dir=getwd()
data <- read.csv("data.csv",header = TRUE, sep=",")
plot_missing(data, percent = TRUE)
plot_missing(data, percent = FALSE)

```

<!--chapter:end:04-missing.Rmd-->

```{r include=FALSE, cache=FALSE}
knitr::opts_chunk$set(
  echo = FALSE,
  message = FALSE,
  warning = FALSE
)
```
# Results

<!--chapter:end:05-results.Rmd-->

```{r include=FALSE, cache=FALSE}
knitr::opts_chunk$set(
  echo = FALSE,
  message = FALSE,
  warning = FALSE
)
```
# Interactive component



<!--chapter:end:06-interactive.Rmd-->

```{r include=FALSE, cache=FALSE}
knitr::opts_chunk$set(
  echo = FALSE,
  message = FALSE,
  warning = FALSE
)
```
# Conclusion


<!--chapter:end:07-conclusion.Rmd-->

